#include "level.h"

const Tiles level_one[] = {
	WALL, WALL, WALL, WALL, WALL, WALL, WALL,WALL,  WALL, WALL,
	WALL, NONE, NONE, NONE, WALL, NONE, NONE, NONE, NONE, WALL,
	WALL, NONE, NONE, NONE, WALL, NONE, NONE, NONE, NONE, WALL,
	WALL, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, WALL,
	WALL, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, WALL,
	WALL, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, WALL,
	WALL, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, WALL,
	WALL, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, WALL,
	WALL, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, WALL,
	WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL,
};

const Level levels[] = {
	{
		.level = ((Tiles *)level_one),
		.width = 10,
		.height = 10,
	},
};

Level GetLevel(int index){
	return levels[index];
}
